---
application:
  name: "api"
  project: "MicoLeaoDublado"
  organization: "QoveryCommunity"
databases:
- type: "MONGODB"
  name: "mongo"
  version: "4.4"
routers:
- name: "main-api"
  routes:
  - application_name: "api"
    paths:
    - "/*"
