version: '3.0'
services:
    addon:
        build: .
        command: start
        ports:
            - "3000:3000"
        networks: 
            - db-connection
        environment: 
            SCRAPER_API_HOST: https://api2-siteplaceholder.herokuapp.com
            PORT: 3000
            DB_HOST: mongo
            DB_PORT: 27017
            DB_NAME: brazilian-stremio-addon
            WAIT_HOSTS: mongo:27017
            WAIT_HOSTS_TIMEOUT: 120
            WAIT_AFTER_HOSTS: 15
    mongo:
        image: mongo:4.2.6-bionic
        ports:
            - "27017:27017"
        networks: 
            - db-connection
        volumes:
            - db:/data/db
            - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js
networks: 
    db-connection:
volumes: 
    db: