name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make build
    - run: make test-ci
  startup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make start &
    - run: curl --fail -sv  http://localhost:3000/manifest.json --connect-timeout 120 --retry 24 --retry-delay 5 --retry-connrefused